--insert into product_gallery(product_id, images) values (9, 'calendar1.jpg, calendar2.jpg, calendar3.webp');
--insert into product_gallery(product_id, images) values (1, 'print_breton.webp');
--insert into product_gallery(product_id, images) values (2, 'print_antihero.webp');
--insert into product_gallery(product_id, images) values (3, 'print_lemondou.webp');
--insert into product_gallery(product_id, images) values (4, 'print_simulan.webp');
--insert into product_gallery(product_id, images) values (5, 'cover_cataract.webp');
--insert into product_gallery(product_id, images) values (6, 'cover_sixtypercent.webp');
--insert into product_gallery(product_id, images) values (7, 'cover_haus.webp');
--insert into product_gallery(product_id, images) values (8, 'cover_kalimutan.webp');
--insert into product_gallery(product_id, images) values (10, 'charms-wfh.webp');
--insert into product_gallery(product_id, images) values (11, 'charms-gamer.webp');
--insert into product_gallery(product_id, images) values (12, 'charms-gentle.webp');
insert into product_gallery(product_id, images) values (13, 'print_timespent.webp');
insert into product_gallery(product_id, images) values (14, 'print_sweet.webp');
insert into product_gallery(product_id, images) values (15, 'print_ikea.webp');
insert into product_gallery(product_id, images) values (16, 'print_spottedpig.webp');
