CREATE TABLE settings (
  id INTEGER NOT NULL PRIMARY KEY,
  store_name VARCHAR(100) NOT NULL,
  store_code VARCHAR(50) NOT NULL UNIQUE,
  logo VARCHAR(50),
  address TEXT,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
