
INSERT INTO products VALUES (NULL, "Cataract", "", 2, 25000, CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(NULL, "There's a 60% chance of rain", "", 2, 25000, CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(NULL, "Haus of Sisig", "", 2, 25000, CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(NULL, "Kalimutan Mo Na Lang Ang Lahat", "", 2, 25000, CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
