DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS order_products;
DROP TABLE IF EXISTS shipping;
DROP TABLE IF EXISTS socials;
DROP TABLE IF EXISTS product_inventory;

