CREATE TABLE product_links (
  id INTEGER NOT NULL PRIMARY KEY,
  product_id INTEGER,
  url VARCHAR(100) DEFAULT '',
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id)
);

